name: Receive and Create Plugin Release

on:
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact from other repo
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.RELEASE_TKN }}
          name: plugin-package
          workflow: upload-artifact.yml
          repo: Fabi-P/fw-custom-meta
          path: release-assets

      - name: Extract metadata
        id: meta
        run: |
          version=$(jq -r .version release-assets/info.json)
          changelog=$(jq -r '.sections.changelog // empty' release-assets/info.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "changelog=$changelog" >> "$GITHUB_OUTPUT"
  
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.meta.outputs.version }}
          name: Release v${{ steps.meta.outputs.version }}
          body: |
            * ${{ steps.meta.outputs.changelog }}

            Files:
            - fw-custom-meta.zip
            - info.json
          draft: true
          files: |
            release-assets/fw-custom-meta.zip
            release-assets/info.json
